services:
  - type: web
    name: tai-po-runaway
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: STAFF_PASSWORD
        sync: false
      - key: HUNTER_PASSWORD
        value: "123456"
